#! /bin/bash
read -p "are you sure you want to delete exe-10?[y/n]" confirm
if [ $confirm == y ]
then
echo "deleting exe-10..."
cd ..
cd apps
rm app-exe-10
echo "exe-10 deleted"
fi
if [ $confirm == Y ]
then
echo "deleting exe-10..."
cd ..
cd apps
rm app-exe-10
echo "exe-10 deleted"
fi
if [ $confirm == n ]
then
echo "deleting of file was cancelled by user"
fi
if [ $confirm == N ]
then
echo "deleting of file was cancelled by user"
fi
cd ..
./app-prompt
