#! /bin/bash
read -p "are you sure you want to delete exe-3?[y/n]" confirm
if [ $confirm == y ]
then
echo "deleting exe-3..."
cd ..
cd apps
rm app-exe-3
echo "exe-3 deleted"
fi
if [ $confirm == Y ]
then
echo "deleting exe-3..."
cd ..
cd apps
rm app-exe-3
echo "exe-3 deleted"
fi
if [ $confirm == n ]
then
echo "deleting of file was cancelled by user"
fi
if [ $confirm == N ]
then
echo "deleting of file was cancelled by user"
fi
cd ..
./app-prompt
