#! /bin/bash
read -p "are you sure you want to delete exe-9?[y/n]" confirm
if [ $confirm == y ]
then
echo "deleting exe-9..."
cd ..
cd apps
rm app-exe-9
echo "exe-9 deleted"
fi
if [ $confirm == Y ]
then
echo "deleting exe-9..."
cd ..
cd apps
rm app-exe-9
echo "exe-9 deleted"
fi
if [ $confirm == n ]
then
echo "deleting of file was cancelled by user"
fi
if [ $confirm == N ]
then
echo "deleting of file was cancelled by user"
fi
cd ..
./app-prompt
