#! /bin/bash
echo "starting the setup"
chmod +x start
cd exec
chmod +x app-prompt
cd chmod
chmod +x chmod-exe-1
chmod +x chmod-exe-2
chmod +x chmod-exe-3
chmod +x chmod-exe-4
chmod +x chmod-exe-5
chmod +x chmod-exe-6
chmod +x chmod-exe-7
chmod +x chmod-exe-8
chmod +x chmod-exe-9
chmod +x chmod-exe-10
cd ..
cd del
chmod +x rm-exe-1
chmod +x rm-exe-2
chmod +x rm-exe-3
chmod +x rm-exe-4
chmod +x rm-exe-5
chmod +x rm-exe-6
chmod +x rm-exe-7
chmod +x rm-exe-8
chmod +x rm-exe-9
chmod +x rm-exe-10
echo "finished setup"
